// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "ToolWindow.31a000cc-8120-41fe-9067-2fb52d4b78d2";
        public const string Name = "ToolWindow";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
