// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Options
{
    internal sealed partial class Vsix
    {
        public const string Id = "Options.58b264d3-2696-404b-b050-1d1e5202192a";
        public const string Name = "Options";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
