// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SingleFileGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "SingleFileGenerator.514e283c-668d-4360-94c9-b2d7ed2ff33c";
        public const string Name = "Single File Generator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
