// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SingleFileGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommandVisisiblityString = "525190a4-9c61-4aa5-8319-7c5fb75dae59";
        public static Guid CommandVisisiblity = new Guid(CommandVisisiblityString);

        public const string SingleFileGeneratorString = "525190a4-9c61-4aa5-8319-7c5fb75dae58";
        public static Guid SingleFileGenerator = new Guid(SingleFileGeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}